# 插件配置，true为开启，false为关闭
plugin_enable:
  mod: true  # mod用于解锁全部角色、皮肤、装扮等
  helper: true  # helper用于将对局发送至雀魂小助手，不使用小助手请勿开启
# liqi用于解析雀魂消息
liqi:
  auto_update: true  # 是否自动更新
<<<<<<< HEAD
  liqi_version: v0.11.104.w # 本地liqi文件版本
=======
  liqi_version: v0.11.86.w # 本地liqi文件版本
>>>>>>> 8b3d5afc280288a703efc69b9e1889e554b2cc45
